# 영토 격자를 적용할 월드 이름
world: world

# 영토 한 칸의 크기 (100 = 100x100)
cell-size: 100

# 동시에 존재할 수 있는 팀의 최대 개수
max-teams: 6

# 팀 스폰 사이에 반드시 유지되어야 하는 최소 거리(블록)
min-team-spawn-distance: 500

# 게임 최대 진행 시간(분). 이 시간이 지나면 그 시점 영토 최다 팀이 승리로 강제 종료됩니다.
# 기본값 10080분 = 7일
max-game-duration-minutes: 10080
